theme = "tokyonight"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
true-color = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error" # Show inline diagnostics when the cursor is on the line
other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line

[keys.normal]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"
